# Generated by Django 5.0.6 on 2024-07-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='firm_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=200)),
                ('gstin', models.CharField(max_length=15)),
                ('phone', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
