# Generated by Django 5.0.6 on 2024-07-19 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_firm_info_username_alter_firm_info_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('status', models.CharField(choices=[('req', 'requested'), ('acpt', 'accepted'), ('com', 'completed')], default='req', max_length=10)),
                ('total_amount', models.IntegerField()),
                ('firm_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.firm_info')),
                ('username', models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
