# Generated by Django 5.0.6 on 2024-07-19 14:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_orders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='orders',
            new_name='order',
        ),
    ]
