# Generated by Django 5.0.6 on 2024-07-19 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_orders_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('req', 'requested'), ('acpt', 'accepted'), ('com', 'completed'), ('can', 'cancelled')], default='req', max_length=10),
        ),
        migrations.CreateModel(
            name='order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breadth', models.FloatField()),
                ('height', models.FloatField()),
                ('length', models.FloatField()),
                ('category', models.CharField(choices=[('col', 'colour'), ('wht', 'white')], default='col', max_length=10)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField(default=0)),
                ('acceptance', models.TextField()),
                ('order_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='website.order')),
            ],
        ),
    ]
