# Generated by Django 5.0.6 on 2024-07-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_user_table_alter_firm_info_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Requested', max_length=10),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='category',
            field=models.CharField(choices=[('Colour', 'Colour'), ('White', 'White')], default='Colour', max_length=10),
        ),
    ]
