# Generated by Django 5.0.6 on 2024-09-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_order_status_alter_order_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm_info',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
