# Generated by Django 5.0.6 on 2025-03-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_firm_info_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='category',
            field=models.CharField(choices=[('One_Side_Colour', 'Two_Side_Colour'), ('Two_Side_Colour', 'Two_Side_Colour'), ('White', 'White')], default='White', max_length=20),
        ),
    ]
