# Generated by Django 5.0.6 on 2025-05-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='firm_info',
            field=models.CharField(max_length=100),
        ),
    ]
