# Generated by Django 5.0.6 on 2025-05-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_reports_firm_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
